# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayload.proto\x12\x07payload\"\x1b\n\x05\x45mpty\x12\x12\n\nsize_in_kb\x18\x01 \x01(\x03\"\x1f\n\x0fPayloadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32M\n\x0ePayloadService\x12;\n\x0fGetLargePayload\x12\x0e.payload.Empty\x1a\x18.payload.PayloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=53
  _globals['_PAYLOADRESPONSE']._serialized_start=55
  _globals['_PAYLOADRESPONSE']._serialized_end=86
  _globals['_PAYLOADSERVICE']._serialized_start=88
  _globals['_PAYLOADSERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
