# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payload/payload.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/payload/payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/payload/payload.proto\x12\x07payload\x1a\x1cgoogle/api/annotations.proto\"$\n\x0ePayloadRequest\x12\x12\n\nsize_in_kb\x18\x01 \x01(\x03\"\x1f\n\x0fPayloadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32h\n\x0ePayloadService\x12V\n\x0fGetLargePayload\x12\x17.payload.PayloadRequest\x1a\x18.payload.PayloadResponse\"\x10\x82\xd3\xe4\x93\x02\n\x12\x08/payloadB/Z-github.com/timothy-jeong/grpc_vs_rest/payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payload.payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/timothy-jeong/grpc_vs_rest/payload'
  _globals['_PAYLOADSERVICE'].methods_by_name['GetLargePayload']._loaded_options = None
  _globals['_PAYLOADSERVICE'].methods_by_name['GetLargePayload']._serialized_options = b'\202\323\344\223\002\n\022\010/payload'
  _globals['_PAYLOADREQUEST']._serialized_start=70
  _globals['_PAYLOADREQUEST']._serialized_end=106
  _globals['_PAYLOADRESPONSE']._serialized_start=108
  _globals['_PAYLOADRESPONSE']._serialized_end=139
  _globals['_PAYLOADSERVICE']._serialized_start=141
  _globals['_PAYLOADSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
